### ISSUE TITLE
AWS keys with special characters break the upload and create a misleading error

### ISSUE THREAD

**Issue by thyming** [drone-plugins/drone-s3#6] opened 2015-11-23 17:55 UTC
When using aws access keys that have non-alphanumeric characters, I get the following error from the aws cli tool:

A client error (SignatureDoesNotMatch) occurred when calling the CreateMultipartUpload operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.

This is a misleading error but goes away when I use access keys that do not contain special characters. Not sure whether the fix has to do with some kind of escaping here or this is just a bug in the aws cli app.

**Comment by bradrydzewski** [comment] 2015-11-23 19:18
marking as help wanted. If someone is able to identify the root cause (drone issue vs s3 cli issue, etc) and issue a pull request I'll be happy to review and merge

**Comment by thyming** [comment] 2015-11-23 19:24
Seems to be because of this: https://github.com/aws/aws-cli/issues/602
They've closed the issue but people are reporting the same thing that I experienced, namely that a plus sign blows things up.

**Comment by thyming** [comment] 2015-11-23 19:25
FWIW I just regenerated keys until I got one without special characters :(((

**Comment by thyming** [comment] 2015-11-23 19:26
If I get a chance this week I'll make a PR that uses the aws sdk instead of the cli.

**Comment by bradrydzewski** [comment] 2015-11-23 19:29
@thyming thanks that would be great! A community member has also been migrating the `s3-sync` plugin to use the native Go sdk. You can see this branch for reference https://github.com/drone-plugins/drone-s3-sync/tree/native

**Comment by thyming** [comment] 2015-11-25 14:14
In the use case of drone exporting an artifact, it seems like drone-s3-sync and this module can be collapsed into one. This module with the recursive option does the same thing as sync, no?

**Comment by bradrydzewski** [comment] 2016-05-26 20:29
closing since we've updated to use the native Go client. Not sure yet if we'll merge `s3` and `s3` sync into a single repository, but this should be solved in 0.5 version of drone

**Closed by bradrydzewski** 2016-05-26 20:29 UTC
Labels: help wanted
